### ISSUE TITLE
Some explanation

### ISSUE THREAD

**Issue by allrude** [phproberto/joomla-entity#2]
Hi Roberto, if been following you progress developing joomla-entity, joomla-common, joomla-component, joomla-module, over the last weeks, but would like some explanation <?=  i'm not that smart ;-) ?> so if you could write a blog post or have some practical instructions that would be nice, perhaps then i'm able to test.

greetings Ruud

**Comment by phproberto** [comment]
Hi Ruud, 

thanks for checking this and getting interested in testing. 

My main goal with all these repositories are:

* **Order my current libraries** in a way that anybody can use them as small parts (myself included). For instance, if I need to create a module I can only require `joomla-module` and install it with my custom module.
* **Natural evolution for code**. If a library has 0 interest it can be easily abandoned only affecting those libraries depending on it.
* **This is not a RAD** like [FOF](https://github.com/akeeba/fof) but a set of libraries like those in the [joomla-framework](https://github.com/joomla-framework/) packages.
* **Share my vision** about how composer-available libraries should be distributed in joomla. So if 5 extensions use `monolog` they don't all have to distribute it with 5 different versions but relaying in the user to solve any conflict related with any possible version conflict.
* **Check Joomla viability** for a software developer. If you distribute a good tool for free and nobody uses it you better not expect to get paid for other Joomla commercial stuff.

Current repositories are created with this structure in mind:

| | joomla-common | |
| --- | --- | --- |
| joomla-component | joomla-module | joomla-entity |

There are more coming like `joomla-plugin`, etc. 

Structure tries to isolate libraries to allow that someone wanting to contribute to improve `joomla-module` can do it without knowing that any non-related libraries even exist (except `joomla-common`).

Current repositories as you see them now include the pure structure required by composer. So any extension wanting to include one of libraries only need to run something like:

`composer require phproberto/joomla-module`

And they can start using it.

With the first stable release of each library I'm also going to also provide a distributable version of them. So you have a zip file to install the library and play with it or to include it in your extension package.

Distributable libraries are IMO better as a global approach for extensions using composer stuff because it ensures that your site will only use an unique version of your library. Let's say that 2 modules decide to use `joomla-module`. If both decide to use it through composer the site will contain 2 versions of the same library which may lead to unexpected errors if versions are different, etc. 

If they use the distributable version there is only a library installed in `libraries/phproberto_module` that will serve to both modules. Users can also see exactly which version of the library is installed and upgrade it when needed. 

When you install more than one distributable libraries you have an structure like:

* `libraries\phproberto` (joomla-common-library)
* `libraries\phproberto_module` (joomla-module-library)
* `libraries\phproberto_enity` (joomla-entity-library)

And each library automatically loads their dependencies. If you want to use joomla-module library stuff you only have to add this line to your custom line:

```php
JLoader::import('phproberto_module.library');
```

There isn't a lot to test until there is no v1. I want to finish entity collections before doing that and ensure that all the `Article` entity related stuff is there so there is a full example of how entities work.

I'd be happy to upload the libraries repositories for module, entity, etc. if you think it can help for  feedback or improvements. Maybe release a v0.0.1 version of them so you can install them and connect through Gulp (which is the method I use locally to test them vs a joomla installation).

Thanks again for checking this.

**Comment by allrude** [comment]
Thanks for your extensive answer Roberto, wil have to read it a second time ;-), wil do so this weekend, Yes i'd like to help and that starts with learning so i wil setup a dev on my MAC, i'm used to work with grunt, but gulp shouldn't be a problem (bit more JS alike) 

have a good weekend

Ruud

**Comment by anibalsanchez** [comment]
**Joomla Entity** is being introduced, right now: https://twitter.com/anibal_sanchez/status/911537134292611072

**Comment by phproberto** [comment]
Closing this as there are now docs explaining things:

https://phproberto.github.io/joomla-entity/
